version: "3.9"

services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx_container
    image: nginx_image
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/wordpress
    restart: always
    networks:
      - localhost

  wordpress:
    build:
      context: ./requirements/wordpress
      args:
        DATABASE: $MYSQL_DATABASE
        USER: $MYSQL_USER
        PASSWORD: $MYSQL_PASSWORD
        HOSTNAME: $MYSQL_HOSTNAME
    container_name: wordpress_container
    image: wordpress_image
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/wordpress
    restart: always
    networks:
      - localhost
    env_file: 
      - .env

  mariadb:
    build:
      context: ./requirements/mariadb
      args:
        DATABASE: $MYSQL_DATABASE
        USER: $MYSQL_USER
        PASSWORD: $MYSQL_PASSWORD
    container_name: mariadb_container
    image: mariadb_image
    volumes:
      - db:/var/lib/mysql
    restart: always
    networks:
      - localhost
    env_file: 
      - .env

networks:
  localhost:
    name: lcadogan.42.fr
    driver: bridge

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/lcadogan/data/wordpress
  db:
    name: db
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/lcadogan/data/mysql
